### ISSUE TITLE
エラーを確認

### ISSUE THREAD

**Issue by tomo0611** [GenbuHase/ArticleEditor#2]
TypeError: Cannot read property 'replace' of undefined
    at app.post (/home/tomo/Documents/ArticleEditor-1.0.0/app.js:69:51)
    at Layer.handle [as handle_request] (/home/tomo/Documents/ArticleEditor-1.0.0/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tomo/Documents/ArticleEditor-1.0.0/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/tomo/Documents/ArticleEditor-1.0.0/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/tomo/Documents/ArticleEditor-1.0.0/node_modules/express/lib/router/layer.js:95:5)
    at /home/tomo/Documents/ArticleEditor-1.0.0/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/tomo/Documents/ArticleEditor-1.0.0/node_modules/express/lib/router/index.js:335:12)
    at next (/home/tomo/Documents/ArticleEditor-1.0.0/node_modules/express/lib/router/index.js:275:10)
    at methodOverride (/home/tomo/Documents/ArticleEditor-1.0.0/node_modules/method-override/index.js:79:5)
    at Layer.handle [as handle_request] (/home/tomo/Documents/ArticleEditor-1.0.0/node_modules/express/lib/router/layer.js:95:5)

環境
OS : Ubuntu 4.4.0-112-generic
Memory : 8GB
Storage : 170GB

**Comment by GenbuHase** [comment]
issueありがとうございます。
恐らくarticlesディレクトリが空の時に起きる不具合ですね。

直ちに修正します。助かります(*･ω･)*_ _)

**Comment by GenbuHase** [comment]
こちらのコミット(#3)にて改善しました。
ありがとうございました。
